server:
  port: 18082
#配置数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/purchase?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yp200134
    driver-class-name: com.mysql.cj.jdbc.Driver

# Mybatis配置:开启sql日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/*.xml